name: my_suit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  easy_localization: ^3.0.3
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
    - assets/font/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/font/Amiri-Regular.ttf
